config/routes.rb
HtscsCom::Application.routes.draw do
  
  get "downloads/index"

  root :to => "home#show"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]  
  resources :supports, :only => [:new, :create]
  resources :contacts, :only => [:new, :create]

  match "/home",                        :to => "home#show"
  match "/work_in_progress",            :to => "home#work_in_progress"
  match "/partners",                    :to => "partners#index"
  match "/prodotti",                    :to => "products#index"
  match "/prodotti_atmedia_infoguard",  :to => "products#show_atmedia_infoguard"
  match "/prodotti_chameleon",          :to => "products#show_chameleon"
  match "/prodotti_hopf",               :to => "products#show_hopf"
  match "/prodotti_ifs9000",            :to => "products#show_ifs9000"
  match "/prodotti_shunra",             :to => "products#show_shunra"
  match "/prodotti_visara",             :to => "products#show_visara"
  match "/soluzioni_crittografia",      :to => "solutions#show_encryption"
  match "/soluzioni_infrastruttura",    :to => "solutions#show_infrastruttura"
  match "/soluzioni_mainframe_open",    :to => "solutions#show_main_open"
  match "/soluzioni_rete_locale_geo",   :to => "solutions#show_rete_locale_geo"
  match "/azienda",                     :to => "companies#show"
  match "/contatti",                    :to => "contacts#new"
  match "/supporto",                    :to => "supports#new"
  match "/download",                    :to => "downloads#index"
  
  match "/signup",                      :to => "users#new"
  match "/signin",                      :to => "sessions#new"
  match "/signout",                     :to => "sessions#destroy"  


  #  resources :xxxs
  #
  # HTTP  | URL         | Action   | Named route     | Purpose
  # -----------------------------------------------------------------------------
  # GET     /xxxs/new     new        new_xxx_path      page to make a new xxx
  #
  # POST    /xxxs         create     xxxs_path          create a new xxx
  #
  # GET     /xxxs         index      xxxs_path         page to list all xxx
  #
  # GET     /xxxs/1       show       xxx_path(1)       page to show xxx with ID 1
  #
  # GET     /xxxs/1/edit  edit       edit_xxx_path(1)  page to edit xxx with ID 1
  #
  # PUT     /xxxs/1       update     xxx_path(1)       update xxx with ID 1
  #
  # DELETE  /xxxs/1       destroy    xxx_path(1)       delete xxx with ID 1
end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= @user.errors.full_messages.length %>
      <% if @user.errors.full_messages.length != 1 %>
        errori hanno 
      <% else %>
        errore ha
      <% end %>
      impedito all'utente di essere salvato:
    </h2>
    <p>Ci sono problemi con i seguenti campi:</p>
    <ul>
      <% @user.errors.full_messages.each do |message|%>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  
<% end %>

app/views/shared/_nav_menu.html.erb
<div id="indexlogo">


  <div id="upmenu">
    <% if signed_in? %>
      <%= link_to "logout", signout_path, :class => @signed_in_class %>
    <% else %>
      <%= link_to "Login", signin_path, :class => @signed_in_class %>
    <% end %>
  	<%= link_to "Contatti", contatti_path, :class => @contatti_class %>
  	<%= link_to "site map", contatti_path, :class => @site_map_class %>
  </div>
  
	<div id="socialicons">  
	  <% image_path_png = "/assets/social_networks/facebook.png" %>
    <% image_title = "facebook htscs"%>
    <% dropbox_path_public_pdf = "http://www.facebook.com/pages/HtSCS/120082184723711" %>
    <% image = image_tag( image_path_png, :id => 18, :alt => image_title, :width => "35", :height => "35", :class => "") %>
    <%= link_to image, dropbox_path_public_pdf, :target => "_blank"  %>
    

	  <% image_path_png = "/assets/social_networks/twitter.png" %>
    <% image_title = "twitter htscs"%>
    <% dropbox_path_public_pdf = "http://twitter.com/htscs" %>
    <% image = image_tag( image_path_png, :id => 18, :alt => image_title, :width => "35", :height => "35", :class => "") %>
    <%= link_to image, dropbox_path_public_pdf, :target => "_blank"  %>


    <% image_path_png = "/assets/social_networks/rss.png" %>
    <% image_title = "rss htscs"%>
    <% dropbox_path_public_pdf = "http://www.accredia.it//ppsearch/accredia_companymask.jsp?ID_LINK=266&area=7&PPSEARCH_COMPANY_CERTIFICATE_NAME=%2550+100+11393%25&PPSEARCH_COMPANY_CERTIFICATE_DATE_FROM=&PPSEARCH_COMPANY_CERTIFICATE_DATE_TO=&PPSEARCH_COMPANY_COMPANY_NAME=&PPSEARCH_COMPANY_PIVA=&PPSEARCH_COMPANY_SEARCH_MASK_SCOPO_MULTI=&PPSEARCH_COMPANY_SEARCH_MASK_STATO=&PPSEARCH_COMPANY_SEARCH_MASK_REGIONE=&PPSEARCH_COMPANY_SEARCH_MASK_PROVINCIA=&PPSEARCH_COMPANY_SEARCH_MASK_CITTA=&PPSEARCH_ORG_SEARCH_MASK_ORG_2=&PPSEARCH_ORG_SEARCH_MASK_SETTORE_ACCR=&PPSEARCH_COMPANY_SEARCH_MASK_NORMA=&submit=cerca" %>
    <% image = image_tag( image_path_png, :id => 18, :alt => image_title, :width => "35", :height => "35", :class => "") %>
    <%= link_to image, dropbox_path_public_pdf, :target => "_blank"  %>

  </div>

	<h1>HtSCS</h1> 
	<p><em> Hightech Storage Connectivity System </em></p>
	
</div><!-- end #logo -->


<div class="breadcrumbs">
  <%= @breadcrumbs %>  
</div>

<div id="indexheader" >
    
  <div id="indexmenu">
  	<ul>
  		<li>
  		  <%= link_to "Homepage", root_path, :class => @home_class %>
  		</li>
  		<li>
  		  <%= link_to "Partners", partners_path, :class => @partners_class %>
  		</li>
  		<li>
  		  <%= link_to "Prodotti", prodotti_path, :class => @prodotti_class %>
  		</li>
  		<li>
  		  <%= link_to "Azienda", azienda_path, :class => @azienda_class %>
  		</li>
  		<li>
  		  <%= link_to "Contatti", contatti_path, :class => @contatti_class %>
  		</li>
  		<%# if signed_in_partner? %>
      
        <!-- <li><%= link_to "Partner download", signin_path, :class => @signed_in_class %></li> -->

      <%# else %>
        <li>
          <%= link_to "Download", download_path, :class => @download_class %>
        </li>
      <%# end %>
  	</ul>
  </div>
  <!-- end #menu -->
  
  <!--
  	<div id="search" >
  		<form method="get" action="" >
  			<fieldset>
  				<input type="text" name="s" id="search-text" size="15" /> 
  			</fieldset>
  		</form>
  	</div>
  -->
  <!-- end #search -->

</div>
<!-- end #header -->

app/views/shared/_nav_menu_curr_azienda.html.erb
<div id="menu">
	<ul>
		<li>
		  <%= link_to "Homepage", root_path, :class => "first" %>
		</li>
		<li>
		  <%= link_to "Partners", partners_path %>
		</li>
		<li>
		  <%= link_to "Prodotti", prodotti_path %>
		</li>
		<li>
		  <%= link_to "Azienda", azienda_path, :class => "current_page_item" %>
		</li>
		<li>
		  <%= link_to "Contatti", contatti_path %>
		</li>
		<% if signed_in? %>
      <li><%= link_to "Esci", signout_path %></li>
    <% else %>
      <li><%= link_to "Login", signin_path %></li>
    <% end %>
	</ul>
</div>
<!-- end #menu -->

app/views/shared/_nav_menu_curr_contatti.html.erb
<div id="menu">
	<ul>
		<li>
		  <%= link_to "Homepage", root_path, :class => "first" %>
		</li>
		<li>
		  <%= link_to "Partners", partners_path %>
		</li>
		<li>
		  <%= link_to "Prodotti", prodotti_path %>
		</li>
		<li>
		  <%= link_to "Azienda", azienda_path %>
		</li>
		<li>
		  <%= link_to "Contatti", contatti_path, :class => "current_page_item" %>
		</li>
		<% if signed_in? %>
      <li><%= link_to "Esci", signout_path %></li>
    <% else %>
      <li><%= link_to "Login", signin_path %></li>
    <% end %>
	</ul>
</div>
<!-- end #menu -->

app/views/shared/_nav_menu_curr_home.html.erb
<div id="indexmenu">
	<ul>
		<li>
		  <%= link_to "Homepage", root_path, @home_class %>
		</li>
		<li>
		  <%= link_to "Partners", partners_path %>
		</li>
		<li>
		  <%= link_to "Prodotti", prodotti_path %>
		</li>
		<li>
		  <%= link_to "Azienda", azienda_path %>
		</li>
		<li>
		  <%= link_to "Contatti", contatti_path %>
		</li>
		<% if signed_in? %>
      <li><%= link_to "Esci", signout_path %></li>
    <% else %>
      <li><%= link_to "Login", signin_path %></li>
    <% end %>
	</ul>
</div>
<!-- end #menu -->

app/views/shared/_nav_menu_curr_partners.html.erb
<div id="menu">
	<ul>
		<li>
		  <%= link_to "Homepage", root_path, :class => "first" %>
		</li>
		<li>
		  <%= link_to "Partners", partners_path, :class => "current_page_item" %>
		</li>
		<li>
		  <%= link_to "Prodotti", prodotti_path %>
		</li>
		<li>
		  <%= link_to "Azienda", azienda_path %>
		</li>
		<li>
		  <%= link_to "Contatti", contatti_path %>
		</li>
		<% if signed_in? %>
      <li><%= link_to "Esci", signout_path %></li>
    <% else %>
      <li><%= link_to "Login", signin_path %></li>
    <% end %>
	</ul>
</div>
<!-- end #menu -->

app/views/shared/_nav_menu_curr_prodotti.html.erb
<div id="menu">
	<ul>
		<li>
		  <%= link_to "Homepage", root_path, :class => "first" %>
		</li>
		<li>
		  <%= link_to "Partners", partners_path %>
		</li>
		<li>
		  <%= link_to "Prodotti", prodotti_path, :class => "current_page_item" %>
		</li>
		<li>
		  <%= link_to "Azienda", azienda_path %>
		</li>
		<li>
		  <%= link_to "Contatti", contatti_path %>
		</li>
		<% if signed_in? %>
      <li><%= link_to "Esci", signout_path %></li>
    <% else %>
      <li><%= link_to "Login", signin_path %></li>
    <% end %>
	</ul>
</div>
<!-- end #menu -->

app/views/shared/_portfolio.html.erb
<h2>Portfolio </h2> 
<ul>
	<li>
	  <%= link_to "Xiotech ISE Storage Blades", "http://www.xiotech.com/products-services/ise-storage-blade/", :class => "external_link" , :target => "_blank" %>							
  </li>
	<li>
	  <%= link_to "Crittografia", soluzioni_crittografia_path %>    				    
	</li>
	<li>
	  <%= link_to "Simulatore di Rete Geografica", prodotti_shunra_path %>    				    
	</li>
	<li>
	  <%= link_to "Cabling Manager", prodotti_ifs9000_path %>    				      						  
	</li>
	<li>
	  <%= link_to "Intelligent Cabling", prodotti_ifs9000_path %>    				      						    						  
	</li>
	<li>
	  <%= link_to "Legacy Tape Emulator", prodotti_chameleon_path %>    				      						  
	</li>
	<li>
	  <%= link_to "Fep Emulator", prodotti_visara_path %>  						
	</li>
	<li>
	  <%= link_to "Supporto H24", supporto_path %>    				    
	</li>
</ul>

app/views/shared/_soluzioni.html.erb
<h2>Soluzioni</h2> 
<ul>
	<li>
	  <%= link_to "Archiviazione e Storage", "http://www.xiotech.com/products-services/ise-storage-blade/", :class => "external_link" , :target => "_blank" %>							
  </li>
	<li>
	  <%= link_to "Mainframe ed Open System", soluzioni_mainframe_open_path %>    				    
	</li>
	<li>
	  <%= link_to "Rete Locale e Rete Geografica", soluzioni_rete_locale_geo_path %>    				    
	</li>
	<li>
	  <%= link_to "Sicurezza", soluzioni_crittografia_path %>
	</li>
	<li>
	  <%= link_to "Infrastruttura", soluzioni_infrastruttura_path %>    				    
	</li>
	<li>							
	  <%= link_to "Sincronizzazione", prodotti_hopf_path %>    				    
	</li>
	<li>
	  <%= link_to "Virtualizzazione", work_in_progress_path %>    				    
	</li>
	<li>
	  <%= link_to "Progettazione", work_in_progress_path %>    				    
	</li>
	<li>
	  <%= link_to "Consulenza", work_in_progress_path %>    				    
	</li>
	<li>
	  <%= link_to "Servizio Tecnico", supporto_path %>
	</li>
</ul>