config/routes.rb
HtscsCom::Application.routes.draw do
  
  get "downloads/index"

  root :to => "home#show"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]  
  resources :supports, :only => [:new, :create]
  resources :contacts, :only => [:new, :create]

  match "/home",                        :to => "home#show"
  match "/work_in_progress",            :to => "home#work_in_progress"
  match "/partners",                    :to => "partners#index"
  match "/prodotti",                    :to => "products#index"
  match "/prodotti_atmedia_infoguard",  :to => "products#show_atmedia_infoguard"
  match "/prodotti_chameleon",          :to => "products#show_chameleon"
  match "/prodotti_hopf",               :to => "products#show_hopf"
  match "/prodotti_ifs9000",            :to => "products#show_ifs9000"
  match "/prodotti_shunra",             :to => "products#show_shunra"
  match "/prodotti_visara",             :to => "products#show_visara"
  match "/soluzioni_crittografia",      :to => "solutions#show_encryption"
  match "/soluzioni_infrastruttura",    :to => "solutions#show_infrastruttura"
  match "/soluzioni_mainframe_open",    :to => "solutions#show_main_open"
  match "/soluzioni_rete_locale_geo",   :to => "solutions#show_rete_locale_geo"
  match "/azienda",                     :to => "companies#show"
  match "/contatti",                    :to => "contacts#new"
  match "/supporto",                    :to => "supports#new"
  match "/download",                    :to => "downloads#index"
  
  match "/signup",                      :to => "users#new"
  match "/signin",                      :to => "sessions#new"
  match "/signout",                     :to => "sessions#destroy"  


  #  resources :xxxs
  #
  # HTTP  | URL         | Action   | Named route     | Purpose
  # -----------------------------------------------------------------------------
  # GET     /xxxs/new     new        new_xxx_path      page to make a new xxx
  #
  # POST    /xxxs         create     xxxs_path          create a new xxx
  #
  # GET     /xxxs         index      xxxs_path         page to list all xxx
  #
  # GET     /xxxs/1       show       xxx_path(1)       page to show xxx with ID 1
  #
  # GET     /xxxs/1/edit  edit       edit_xxx_path(1)  page to edit xxx with ID 1
  #
  # PUT     /xxxs/1       update     xxx_path(1)       update xxx with ID 1
  #
  # DELETE  /xxxs/1       destroy    xxx_path(1)       delete xxx with ID 1
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @title = " - prodotti"
    @home_class = "first"
    @prodotti_class = "current_page_item"
    @breadcrumbs = "home > prodotti"
  end

  def show_atmedia_infoguard
    @title = " - crittografia layer2"    
    @home_class = "first"
    @prodotti_class = "current_page_item"
    @breadcrumbs = "home > prodotti > crittografia layer2"
  end

  def show_chameleon
    @title = " - legacy tape emulator"    
    @home_class = "first"
    @prodotti_class = "current_page_item"
    @breadcrumbs = "home > prodotti > legacy tape emulator"
  end

  def show_hopf
    @title = " - master clock"    
    @home_class = "first"
    @prodotti_class = "current_page_item"
    @breadcrumbs = "home > prodotti > master clock"
  end

  def show_ifs9000
    @title = " - cablaggio intelligente"    
    @home_class = "first"
    @prodotti_class = "current_page_item"
    @breadcrumbs = "home > prodotti > cablaggio intelligente"
  end

  def show_shunra
    @title = " - simulatore di rete geografica"    
    @home_class = "first"
    @prodotti_class = "current_page_item"
    @breadcrumbs = "home > prodotti > simulatore rete geografica"
  end

  def show_visara
    @title = " - FEP emulator"    
    @home_class = "first"
    @prodotti_class = "current_page_item"
    @breadcrumbs = "home > prodotti > FEP emulator"
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<%= render 'shared/nav_menu' %>

<div id="indexpage">
	<div id="page-bgtop">
		<div id="content">
			<div class="post">
				<h2 class="title"><a href="#">Prodotti</a></h2> 
				<div class="entry">
					<div class="boxgrid caption">
						<img src="/assets/mainmenu/ise.jpg" alt="xiotech"/> 
						<div class="cover boxcaption">
					    <h3>ISE Storage Blade </h3> 
							<p>
								Xiotech garantisce prestazioni senza precedenti
							  <br />
								<br />
								<%= link_to "leggi...", "http://www.xiotech.com/products-services/ise-storage-blade/", :class => "external_link" , :target => "_blank" %>        			  
							</p>
						</div>
					</div>
					<div class="boxgrid caption">
						<img src="/assets/mainmenu/infoguard.png" alt="infoguard" /> 
						<div class="cover boxcaption">
					    <h3>Infoguard </h3> 
							<p>
								Tecnologia Svizzera per la Sicurezza dei Dati
							  <br />
								<br />
								<%= link_to "leggi...", prodotti_atmedia_infoguard_path, :class => "internal_link"  %>        			  								
							</p>
						</div>
					</div>
					<div class="boxgrid caption">
						<img src="/assets/mainmenu/Cabling.png" alt="cabling"/> 
						<div class="cover boxcaption">
							<h3>IFS9000</h3> 
							<p>
								Cablaggio in fibra ottica “intelligente"
							  <br />
								<br />
								<%= link_to "leggi...", prodotti_ifs9000_path, :class => "internal_link"  %>								
							</p>
						</div>
					</div>
					<div class="boxgrid caption">
						<img src="/assets/mainmenu/Shunra.png" alt="shunra"/> 
						<div class="cover boxcaption">
							<h3>Network Simulator</h3> 
							<p>
								Wan, Web, Mobile, Cloud
								<br />
								<br />
								<%= link_to "leggi...", prodotti_shunra_path, :class => "internal_link"  %>
							</p>
						</div>
					</div>
					<div class="boxgrid caption">
						<img src="/assets/mainmenu/Chamaleon.png" alt="chameleon"/> 
						<div class="cover boxcaption">
							<h3>Legacy Emulator</h3> 
							<p>
								Emulazione CU per utilizzo Legacy Tape 3420,3480,3490
								<br />
								<br />
								<%= link_to "leggi...", prodotti_chameleon_path, :class => "internal_link"  %>
							</p>
						</div>
					</div>
					<div class="boxgrid caption">
						<img src="/assets/mainmenu/Hopf.png" alt="hopf"/> 
						<div class="cover boxcaption">
							<h3>Hopf System</h3> 
							<p>
								Network Time Server
							  <br />
								<br />
								<%= link_to "leggi...", prodotti_hopf_path, :class => "internal_link"  %>								
							</p>
						</div>
					</div>
					
	        <p><img src="/assets/frames_and_lines/separatore.png" alt="separatore" hspace="180" /></p>
					
          <div>
            <%= link_to "torna alla homepage", root_path, :class => "links" %>
					</div>
				
				</div>
	
			</div>
		</div>
		<!-- end #content -->

		<div id="indexsidebar">
			<ul>
				<li>
					<h3>Go Green</h3>
					<p>80% di risparmio energetico, 80% di risparmio di spazio, 80% di risparmio per il raffreddamento, questi sono alcuni dei &quot;Green Benefits&quot; di Xiotech.</p>
				</li>
				<li>
          <%= render 'shared/portfolio' %>
				</li>
				<li>
          <%= render 'shared/soluzioni' %>
				</li>
			</ul>
		</div>
<!-- end #sidebar -->


		<div style="clear: both;">
			&nbsp;
		</div>
	</div>
<!-- end #page -->
</div>


<div id="footer">
	<p>
		Copyright (c) 2011 htscs srl. All rights reserved.
	</p>
</div>
<!-- end #footer -->

app/views/products/show_atmedia_infoguard.html.erb
<%= render 'shared/nav_menu' %>

<div id="indexpage">
  <div id="page-bgtop">
		<div id="content">

			<div class="post">				
			  <h2 class="title"><a href="#">Encryption layer 2 - Infoguard Solutions</a></h2>
			  <div class="entry">
  	      <p>
  	        <img src="/assets/products/InfoguardEG10.png" alt="EtherG10G" width="206" height="156" hspace="5" align="left" />
  	        L'Infoguard Ether Guard 10G è un sistema di crittatura dati ad alte prestazioni per reti 1 e 10Gigabit Ethernet livello 2 con l’utilizzo dello standard AES prestazioni al 100% ed una latenza di &lt;5µs costante. Facile integrazione nella rete e minima manutenzione. Configurazione e monitoraggio centralizzato. Sviluppo ed assemblaggio in Svizzera.  
  	      </p>
  	      <p>&nbsp;</p>    
  				<p>
  				  <img src="/assets/products/InfoguardMG10.png" alt="MG10" width="206" height="156" hspace="5" vspace="15" align="left" />
  				  L'InfoGuard Multilink Encryption è una soluzione di criptatura dati flessibile e vantaggiosa con l’utilizzo dello standard AES per connessioni Ethernet, Fibre Channel e FICON con prestazioni 100% ed una latenza &lt;1µs. Trasmette fino a dieci differenti interfacce attraverso reti CWDM, DWDM, Fibra spenta o SDH. Supporta il Gigabit Ethernet, Fibre Channel 1/2/4 Gbps e FICON 1/2 Gbps. Facile l’integrazione nella rete con minima manutenzione.
  				</p>
  				<p>&nbsp;</p>
  				<p>
  				  <img src="/assets/products/InfoguardEG10_2.png" alt="SonetSDH" width="206" height="156" hspace="5" vspace="5" align="left" />
  				  L'InfoGuard SONET/SDH Encryption è un sistema di crittatura dati su rete SONET/SDH a livello 2 con l’utilizzo dello standard AES prestazioni al 100% ed una latenza minima &lt;1µs. Facile integrazione nella rete esistente STM-64 SONET/SDH. Configurazione  e monitoraggio centralizzato. Sviluppo ed assemblaggio in Svizzera. 
  				</p>
			  </div>
		  </div>
		  
		  <div class="post">
				<p class="meta"> Posted by <a href="#">Marketing Team</a></p>
				<h2 class="title"><a href="#">Encryption layer 2 - ATMedia Solutions</a></h2>
				<div class="entry">
					<p>
					  <img src="/assets/products/ATMediaEthEncryptor100M.png" alt="ATM100" width="206" height="156" hspace="5" align="left" />
					  L'ATMedia Ethernet Encryptor è un sistema di crittatura layer 2 per reti ethernet. La soluzione ha una banda di 100Mbps ed è trasparente al protocollo; si qualifica come un ottimo sistema di crittatura per collegamenti punto punto su rete urbana (MAN).
					</p>
				  <p>&nbsp;</p>
					<p>
					  <img src="/assets/products/ATMediaEthEncryptor1G.png" alt="Encry1Gb" width="206" height="156" hspace="5" vspace="5" align="left" />
					  L'ATMedia Gigabit Ethernet Link Encryptor è un sistema di crittatura layer 2 per reti ethernet. La soluzione ha una banda di 1Gbps ed è trasparente al protocollo. Si qualifica come un ottimo sistema di crittatura per collegamenti punto punto su rete geografica (WAN).
					</p>
				  <p>&nbsp;</p>
          <p>
            <img src="/assets/products/ATMediaEthEncryptor10G.png" alt="Encry10Gb" width="206" height="156" hspace="5" vspace="5" align="left" />
            L'<strong>ATMedia 10G Ethernet Encryptor</strong> è un sistema di crittatura   layer 2 per reti 10 Gigabit Ethernet e OC192/STM64 SONET/SDH. La   soluzione ha una banda di 10Gbps ed è trasparente al protocollo; si   qualifica come un ottimo sistema di crittatura per collegamenti punto   punto su backbone geografica.
          </p>
          <p>&nbsp;</p>
          <p>
            <img src="/assets/products/ATMediaATMEncryptor.png" alt="ATMsdh" width="206" height="156" hspace="5" vspace="5" align="left" />
            L'<strong>ATMedia SDH Encryptor</strong> è un sistema di crittatura   trasparente al protocollo per reti SONET/SDH. L'area di applicazione è   caratterizzata da scenari dove apparati PBX, routers, switches ed   apparati audio/video sono connessi via links OC3, OC12 o OC48 SONET/SDH e   devono essere salvaguardati contro tapping e manipolazioni.
          </p>
        </div>
  			<div>
  			  <%= link_to "torna alla homepage", root_path, :class => "links" %>
  			</div>
			</div>
			
		</div>
    		<!-- end #content -->

    		<div id="indexsidebar">
    			<ul>
    				<li>
    					<h3>Go Green</h3>
    					<p>80% di risparmio energetico, 80% di risparmio di spazio, 80% di risparmio per il raffreddamento, questi sono alcuni dei &quot;Green Benefits&quot; di Xiotech.</p>
    				</li>
    				<li>
              <%= render 'shared/portfolio' %>
    				</li>
    				<li>
              <%= render 'shared/soluzioni' %>
    				</li>
    			</ul>
    		</div>
    <!-- end #sidebar -->


    		<div style="clear: both;">
    			&nbsp;
    		</div>
    	</div>
    <!-- end #page -->
    </div>


    <div id="footer">
    	<p>
    		Copyright (c) 2011 htscs srl. All rights reserved.
    	</p>
    </div>
    <!-- end #footer -->

app/views/products/show_chameleon.html.erb
<%= render 'shared/nav_menu' %>

<div id="indexpage">
  <div id="page-bgtop">
		<div id="content">

			<div class="post">
				<p class="meta"> Posted by <a href="#">Marketing Team</a></p>
				<h2 class="title"><a href="#">Chameleon - Legacy tape emulator</a></h2>
				<div class="entry">
					<p>Chameleon ...</p>
			  </div>
				<div></div>
			</div>
			
			<div class="post">				
				<h2 class="title"><a href="#">Descrizione tecnica</a></h2>
				<div class="entry">
					<p> Il sistema si basa su un hardware ...</p>
			  </div>
				<div>
				  <%= link_to "torna alla homepage", root_path, :class => "links" %>  			  
				</div>
		  </div>

		</div>
    		<!-- end #content -->

    		<div id="indexsidebar">
    			<ul>
    				<li>
    					<h3>Go Green</h3>
    					<p>80% di risparmio energetico, 80% di risparmio di spazio, 80% di risparmio per il raffreddamento, questi sono alcuni dei &quot;Green Benefits&quot; di Xiotech.</p>
    				</li>
    				<li>
              <%= render 'shared/portfolio' %>
    				</li>
    				<li>
              <%= render 'shared/soluzioni' %>
    				</li>
    			</ul>
    		</div>
    <!-- end #sidebar -->


    		<div style="clear: both;">
    			&nbsp;
    		</div>
    	</div>
    <!-- end #page -->
    </div>


    <div id="footer">
    	<p>
    		Copyright (c) 2011 htscs srl. All rights reserved.
    	</p>
    </div>
    <!-- end #footer -->

app/views/products/show_hopf.html.erb
<%= render 'shared/nav_menu' %>

<div id="indexpage">
  <div id="page-bgtop">
		<div id="content">
			<div class="post">
				<p class="meta"> Posted by <a href="#">Marketing Team</a></p>
				<h2 class="title"><a href="#">Sincronizzazione</a></h2>
				<div class="entry">
					<h4>L'importanza di essere sincronizzati</h4>
					<p>Avere uno stesso sitema di riferimento è importante in ogni ambito, e questo è ancor più vero in ambienti in cui i tempi di risposta e le elaborazioni delle informazioni viaggiano a velocità elevate. Una squadra gioca bene se è coordinata e precisa nell'eseguire gli schemi di gioco. Lo stesso vale nell'infrastruttura IT. A &quot;dare il tempo&quot; per un perfetto sincronismo all'interno dell'infrastruttura IT sono gli apparati di rete denominati Network Time Servers (o Masterclocks).</p>
				</div>
				<div></div>
			</div>
			<div class="post">
				
				<h2 class="title"><a href="#">Network Time Servers</a>				</h2>
				<div class="entry">
					<p>Network Time Servers

La loro funzione è quella di essere il riferimento orario per tutti gli apparati dotati di un proprio orologio interno (quarzo) che possano ricevere un qualsivoglia segnale di sincronizzazione. Nel mondo degli affari di oggi, altamente tecnologico, un Network Time Server è un elemento fondamentale dell'infrastruttura IT. Un network time server fornisce un modo semplice ed efficiente per sincronizzare il clock interno di desktop, servers, ed altri apparati connessi alla rete aziendale. Il network time server permette di sincronizzare la rete aziendale con un segnale esterno estremamente accurato fornito dagli orologgi atomici installati sui satelli del sistema GPS. Questo fa sì che le transazioni e le comunicazioni fra reti aziendali diverse possano essere strettamente sincronizzate. Senza un nts l'azienda può andare in contro ad un numero elevato di problemi che possono impattare sulle performance se non addirittura danneggiare il business.

Vantaggi della sincronizzazione in ambito industriale:
    </p>
					<p>* sincronizzazione dei sistemi di controllo (DCS e PLC)
				  </p>
					<p>* sincronizzazione registratori di eventi
				    </p>
					<p>* sincronizzazione e funzionalità dei sistemi di protezioni elettriche
					  
					  Vantaggi della sincronizzazione in ambito IT:
				    </p>
					<p>* performance negli apparati di rete che processano in funzione dei timestamp
				    </p>
					<p>* performance e funzionalità per le applicazioni a livello OSI7 basate sui timestamp
				    </p>
					<p>* ricerca di guasti o malfunzionamenti tra le logs dei vari apparati
				    </p>
					<p>* performance e funzionalità nei database transazionali distribuiti
				    </p>
					<p>* Affidabilità nel journalling e nel logging
				    </p>
					<p>* Performance e funzionalità nel mercato azionario e nel processamento degli ordini
				    </p>
					<p>* Affidabilità nel Secure document timestamps, richiesto nelle certifiche di crittatura.
				    </p>
					<p>* Affidabilità nei sistemi di sicurezza quali ID (Intrusion Detection) e IPS (Intrusion Prevention System)
				    </p>
					<p>* Sincronizzazione di applicativi multimedia per teleconferenze in tempo reale
				    </p>
					<p>* Monitoraggio e controllo della rete aziendale
				    </p>
					<p>* Individuazione anticipata di malfunzionamenti di alcuni apparati sulla rete.
				    </p>
					<p>* Affidabilità, funzionalità e performance nei servizi di &quot;traffic engineering&quot; quali il &quot;differentiated services&quot; per reti MPLS.
				    </p>
				  <p>* Affidabilità, funzionalità e performance nelle reti distribuite per l'addestramento professionale. </p>
                  <h4> Come funziona il GPS</h4>
                    <p> Ad un'altezza di circa 20.000km dei satelliti girano intorno alla terra due volte al giorno su 6 orbite differenti formando una rete che avvolge la terra. Il primo sistema GPS fu sviluppato sulla base di 21 satelliti di cui 3 di riserva. Col passare del tempo il numero di satelliti è passato a 27 per coprire possibili mancanze di copertura per brevi periodi. Da 6 ad 11 di questi satelliti sono sono visibili da ogni punto della terra per tutto il tempo. A bordo ogni satellite ha un orologio atomico ad alta precisione (1x10-12) Una frequenza base di 10.23 Mhz è derivata dalla frequenza dell'orologio atomico. Questa frequenza viene inviata attraverso due segnali di trasporto L1 ed L2 elaborati sulla stessa frequenza base.    </p>
                    <p>* la frequenza di trasmissione L1 = 154 * 10,23 = 1575,42Mhz                      </p>
                    <p>* la frequenza di trasmissione L2 = 120 * 10,23 = 1227,60Mhz                      </p>
                    <p>I segnali trasmessi da ogni satellite vengono interpolati ed utilizzati per i sistemi di navigazione e di sincronizzazione. I dati della frequenza L1 possono essere decodificati per uso civile. Il tempo esatto può essere calcolato da queste informazioni e dalla posizione che viene stabilita dall'antenna. </p>
              </div>
				<div>
  			  <%= link_to "torna alla homepage", root_path, :class => "links" %>
				</div>
		  </div>
		</div>
    		<!-- end #content -->

    		<div id="indexsidebar">
    			<ul>
    				<li>
    					<h3>Go Green</h3>
    					<p>80% di risparmio energetico, 80% di risparmio di spazio, 80% di risparmio per il raffreddamento, questi sono alcuni dei &quot;Green Benefits&quot; di Xiotech.</p>
    				</li>
    				<li>
              <%= render 'shared/portfolio' %>
    				</li>
    				<li>
              <%= render 'shared/soluzioni' %>
    				</li>
    			</ul>
    		</div>
    <!-- end #sidebar -->


    		<div style="clear: both;">
    			&nbsp;
    		</div>
    	</div>
    <!-- end #page -->
    </div>


    <div id="footer">
    	<p>
    		Copyright (c) 2011 htscs srl. All rights reserved.
    	</p>
    </div>
    <!-- end #footer -->

app/views/products/show_ifs9000.html.erb
<%= render 'shared/nav_menu' %>

<div id="indexpage">
  <div id="page-bgtop">
		<div id="content">

			<div class="post">
				<p class="meta"> Posted by <a href="#">Marketing Team</a></p>
				<h2 class="title"><a href="#">IFS9000 Cablaggio Intelligente</a></h2>
				<div class="entry">
					<p>IFS9000 aiuta le aziende a sviluppare i requisiti di un “nuovo” datacenter con l’offerta della sua linea di cablaggio in fibra ottica “intelligente”. I sistemi in fibra ottica IFS9000 sono progettati per minimizzare la richiesta di spazio rack fornendo pannelli e cabinet modulari che incorporano un’intelligenza hardware e software. Quest’intelligenza “embedded” semplifica le procedure di implementazione, manutenzione e gestione dei collegamenti in fibra di tutto il CED. rendendo le connessioni veloci, affidabili e “visivamente guidate”, il sistema IFS9000 riduce drasticamente i tempi richiesti per la pianificazione ed attuazione di spostamenti, aggiunte e cambi di configurazione eliminando problematiche di disservizi dovute ad errori di configurazione o di installazione.</p>
			  </div>
				<div></div>
			</div>
			
			<div class="post">				
				<h2 class="title"><a href="#">Descrizione tecnica</a></h2>
				<div class="entry">
					<p> Il sistema si basa su un hardware composto da armadi rack centrali e di zona dove sono allocati i pannelli e la parte elettronica di intelligenza. I pannelli supportano tutti i tipi di connettori in fibra ottica presenti sul mercato e tutti i tipi di standard ( Multi Mode 62,5/125- Multi Mode 50/125 – Single Mode 9/125 OC3) : Escon, SC duplex, LC duplex, SFF, MTRJ, SSDI. I pannelli possono essere composti da 24 fino a 144 porte con un ingombro che varia dalle 3 alle 6 unità. Nella parte posteriore sono presenti i trunks di connessione fra zona o device ( CPU o Director ) con tecnologia MTP ,certificati e configurabili sul sistema di gestione per una rapida individuazione in caso di fault. Ogni porta è identificata in maniera univoca da un LED ed è configurata sul sistema di gestione ( Opti Manager) che ha una GUI grafica dove sono riportati tutti gli armadi , i pannelli, le porte presenti per pannello e le eventuali connessioni con altre porte. Esiste un data-base con tutte le connessioni attive , le porte libere a disposizione e i patchs disponibili per le connessioni. Tramite una procedura guidata denominata work-order, il cliente può facilmente implementare o disimplementare le connessioni dei device presenti nel centro elettronico. Il software genera dei report con tutte le informazioni riguardanti le connessioni attive pannello per pannello, quelle libere, tipologia di fibra, etc. I diagrammi sono personalizzabili dal cliente e con un modulo aggiuntivo è possibile generare un disegno del centro elettronico(CAD) dove sono presenti gli armadi di cablaggio e tutti gli altri device presenti. Per tutti quei clienti che sono già in possesso di un cablaggio intelligente modello IFS9000 della Inrange vi è una totale compatibilità sia dal punto di vista hardware che software fra i due sistemi che diverranno un solo sistema integrato salvaguardando l’investimento.</p>
			  </div>
				<div>
				  <%= link_to "torna alla homepage", root_path, :class => "links" %>  			  
				</div>
		  </div>

		</div>
    		<!-- end #content -->

    		<div id="indexsidebar">
    			<ul>
    				<li>
    					<h3>Go Green</h3>
    					<p>80% di risparmio energetico, 80% di risparmio di spazio, 80% di risparmio per il raffreddamento, questi sono alcuni dei &quot;Green Benefits&quot; di Xiotech.</p>
    				</li>
    				<li>
              <%= render 'shared/portfolio' %>
    				</li>
    				<li>
              <%= render 'shared/soluzioni' %>
    				</li>
    			</ul>
    		</div>
    <!-- end #sidebar -->


    		<div style="clear: both;">
    			&nbsp;
    		</div>
    	</div>
    <!-- end #page -->
    </div>


    <div id="footer">
    	<p>
    		Copyright (c) 2011 htscs srl. All rights reserved.
    	</p>
    </div>
    <!-- end #footer -->

app/views/products/show_visara.html.erb
<%= render 'shared/nav_menu' %>

<div id="indexpage">
  <div id="page-bgtop">
		<div id="content">

			<div class="post">
				<p class="meta"> Posted by <a href="#">Marketing Team</a></p>
				<h2 class="title"><a href="#">Fep emulator</a></h2>
				<div class="entry">
					<p>Lavori in corso ...</p>
			  </div>
				<div></div>
			</div>
			
			<div class="post">				
				<h2 class="title"><a href="#">Descrizione tecnica</a></h2>
				<div class="entry">
					<p> ...</p>
			  </div>
				<div>
				  <%= link_to "torna alla homepage", root_path, :class => "links" %>  			  
				</div>
		  </div>

		</div>
    		<!-- end #content -->

    		<div id="indexsidebar">
    			<ul>
    				<li>
    					<h3>Go Green</h3>
    					<p>80% di risparmio energetico, 80% di risparmio di spazio, 80% di risparmio per il raffreddamento, questi sono alcuni dei &quot;Green Benefits&quot; di Xiotech.</p>
    				</li>
    				<li>
              <%= render 'shared/portfolio' %>
    				</li>
    				<li>
              <%= render 'shared/soluzioni' %>
    				</li>
    			</ul>
    		</div>
    <!-- end #sidebar -->


    		<div style="clear: both;">
    			&nbsp;
    		</div>
    	</div>
    <!-- end #page -->
    </div>


    <div id="footer">
    	<p>
    		Copyright (c) 2011 htscs srl. All rights reserved.
    	</p>
    </div>
    <!-- end #footer -->